<?php

use yii\db\Migration;

class m170525_090136_insert_clock extends Migration
{
    public function up()
    {
        $this->insert('clock',array(
            'name'=>'Тестовая запись часов #1',
            'image_main' =>'https://placeholdit.imgix.net/~text?txtsize=75&txt=250x250&w=250&h=250',
            'images' => 'https://placeholdit.imgix.net/~text?txtsize=75&txt=250x250&w=250&h=250',
            'manufacture' => '1',
            'price' => '1200',
            'gender' => '1',
            'mechanism' => '1',
            'type' => '2',
            'case_material' => '2',
            'case_form' => '2',
            'width' => '50',
            'height' => '50',
            'depth' => '50',
            'water_resistance' => '1',
            'glass' => '1',
            'watchband' => '1',
            'time_display' => '1',
            'dial_symbols' => '1',
            'color_case' => '1',
            'color_watchband' => '1',
            'in_stock' => '1',
            'count' => '10',
            'purchase_price' => '800',
            'hot_price' => '1400',
            'display' => '1',
            'description' => 'test',
        ));

        $this->insert('clock',array(
            'name'=>'Тестовая запись часов #2',
            'image_main' =>'https://placeholdit.imgix.net/~text?txtsize=75&txt=250x250&w=250&h=250',
            'images' => 'https://placeholdit.imgix.net/~text?txtsize=75&txt=250x250&w=250&h=250',
            'manufacture' => '2',
            'price' => '1525',
            'gender' => '1',
            'mechanism' => '1',
            'type' => '2',
            'case_material' => '2',
            'case_form' => '2',
            'width' => '50',
            'height' => '50',
            'depth' => '50',
            'water_resistance' => '1',
            'glass' => '1',
            'watchband' => '1',
            'time_display' => '1',
            'dial_symbols' => '1',
            'color_case' => '1',
            'color_watchband' => '1',
            'in_stock' => '1',
            'count' => '10',
            'purchase_price' => '800',
            'hot_price' => '1600',
            'display' => '1',
            'description' => 'test',
        ));

        $this->insert('clock',array(
            'name'=>'Тестовая запись часов #3',
            'image_main' =>'https://placeholdit.imgix.net/~text?txtsize=75&txt=250x250&w=250&h=250',
            'images' => 'https://placeholdit.imgix.net/~text?txtsize=75&txt=250x250&w=250&h=250',
            'manufacture' => '2',
            'price' => '2500',
            'gender' => '1',
            'mechanism' => '1',
            'type' => '2',
            'case_material' => '2',
            'case_form' => '2',
            'width' => '50',
            'height' => '50',
            'depth' => '50',
            'water_resistance' => '1',
            'glass' => '1',
            'watchband' => '1',
            'time_display' => '1',
            'dial_symbols' => '1',
            'color_case' => '1',
            'color_watchband' => '1',
            'in_stock' => '1',
            'count' => '10',
            'purchase_price' => '800',
            'hot_price' => '2800',
            'display' => '1',
            'description' => 'test',
        ));

        $this->insert('clock',array(
            'name'=>'Тестовая запись часов #4',
            'image_main' =>'https://placeholdit.imgix.net/~text?txtsize=75&txt=250x250&w=250&h=250',
            'images' => 'https://placeholdit.imgix.net/~text?txtsize=75&txt=250x250&w=250&h=250',
            'manufacture' => '2',
            'price' => '800',
            'gender' => '1',
            'mechanism' => '1',
            'type' => '2',
            'case_material' => '2',
            'case_form' => '2',
            'width' => '50',
            'height' => '50',
            'depth' => '50',
            'water_resistance' => '1',
            'glass' => '1',
            'watchband' => '1',
            'time_display' => '1',
            'dial_symbols' => '1',
            'color_case' => '1',
            'color_watchband' => '1',
            'in_stock' => '1',
            'count' => '10',
            'purchase_price' => '600',
            'hot_price' => '900',
            'display' => '1',
            'description' => 'test',
        ));

        $this->insert('clock',array(
            'name'=>'Тестовая запись часов #5',
            'image_main' =>'https://placeholdit.imgix.net/~text?txtsize=75&txt=250x250&w=250&h=250',
            'images' => 'https://placeholdit.imgix.net/~text?txtsize=75&txt=250x250&w=250&h=250',
            'manufacture' => '2',
            'price' => '900',
            'gender' => '1',
            'mechanism' => '1',
            'type' => '2',
            'case_material' => '2',
            'case_form' => '2',
            'width' => '50',
            'height' => '50',
            'depth' => '50',
            'water_resistance' => '1',
            'glass' => '1',
            'watchband' => '1',
            'time_display' => '1',
            'dial_symbols' => '1',
            'color_case' => '1',
            'color_watchband' => '1',
            'in_stock' => '1',
            'count' => '10',
            'purchase_price' => '600',
            'hot_price' => '900',
            'display' => '1',
            'description' => 'test',
        ));

        $this->insert('clock',array(
            'name'=>'Тестовая запись часов #6',
            'image_main' =>'https://placeholdit.imgix.net/~text?txtsize=75&txt=250x250&w=250&h=250',
            'images' => 'https://placeholdit.imgix.net/~text?txtsize=75&txt=250x250&w=250&h=250',
            'manufacture' => '2',
            'price' => '800',
            'gender' => '1',
            'mechanism' => '1',
            'type' => '2',
            'case_material' => '2',
            'case_form' => '2',
            'width' => '50',
            'height' => '50',
            'depth' => '50',
            'water_resistance' => '1',
            'glass' => '1',
            'watchband' => '1',
            'time_display' => '1',
            'dial_symbols' => '1',
            'color_case' => '1',
            'color_watchband' => '1',
            'in_stock' => '1',
            'count' => '10',
            'purchase_price' => '600',
            'hot_price' => '900',
            'display' => '1',
            'description' => 'test',
        ));
    }

    public function down()
    {
        echo `Revert not allowed. please delete fields by yourself`;
        return true;
    }
}
